name: Rust CI for Rocket App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Rocket App
      working-directory: ./rocketapp
      run: cargo build --verbose
    - name: Run tests for Rocket App
      working-directory: ./rocketapp
      run: cargo test --verbose
