name: Rust CI for Rocket App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/cargo@v1
    - uses: actions-rs/toolchain@v1
      with:
        working-directory: ./rocketapp
        profile: minimal
        toolchain: 1.81.0
        override: true
    - uses: actions-rs/cargo@v1
      with:
        working-directory: ./rocketapp
        command: build
        args: --verbose
    - uses: actions-rs/cargo@v1
      with:
        working-directory: ./rocketapp
        command: test
        args: --verbose
