name: Rust CI for Rocket App
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - uses: actions-rust-lang/setup-rust-toolchain@v1
    #   with:
    #     components: rustfmt
    - name: Build Demo
      working-directory: ./rocketapp
      run: cargo build --verbose
    - name: Run tests for Demo
      working-directory: ./rocketapp
      run: cargo rustc -- --version && rustup show && cargo test --verbose # --all-features
    # - name: Rustfmt Check
    #   uses: actions-rust-lang/rustfmt@v1
